name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        version: [ "3.32.x"]
      # Disable fail-fast; we want results from all OSes even if one fails.
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          path: flutter_platform_alert
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          channel: "stable" # optional, default to: 'stable'
      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ github.workspace }}/flutter_platform_alert/example
      - name: Build macOS
        if: startsWith(matrix.os, 'macOS')
        run: flutter build macos
        working-directory: ${{ github.workspace }}/flutter_platform_alert/example
      - name: Build iOS
        if: startsWith(matrix.os, 'macOS')
        run: flutter build ios --debug --no-codesign --simulator
        working-directory: ${{ github.workspace }}/flutter_platform_alert/example
